"""empty message

Revision ID: 0cfca8bbc912
Revises: 884c8272fdc6
Create Date: 2026-01-10 14:56:18.985610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfca8bbc912'
down_revision: Union[str, None] = '884c8272fdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teachers_user_id', 'teachers', type_='unique')
    op.drop_constraint('fk_teachers_user_id', 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column(
        'user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_teachers_user_id', 'teachers', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_teachers_user_id', 'teachers', ['user_id'])
    # ### end Alembic commands ###
