"""empty message

Revision ID: 0cfca8bbc912
Revises: 884c8272fdc6
Create Date: 2026-01-10 14:56:18.985610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfca8bbc912'
down_revision: Union[str, None] = '884c8272fdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    tables = inspector.get_table_names()

    if "teachers" in tables:
        uniques = {u["name"]
                   for u in inspector.get_unique_constraints("teachers")}
        if "uq_teachers_user_id" in uniques:
            op.drop_constraint("uq_teachers_user_id",
                               "teachers", type_="unique")

        fks = {f["name"] for f in inspector.get_foreign_keys("teachers")}
        if "fk_teachers_user_id" in fks:
            op.drop_constraint("fk_teachers_user_id",
                               "teachers", type_="foreignkey")

        cols = {c["name"] for c in inspector.get_columns("teachers")}
        if "user_id" in cols:
            op.drop_column("teachers", "user_id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column(
        'user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_teachers_user_id', 'teachers', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_teachers_user_id', 'teachers', ['user_id'])
    # ### end Alembic commands ###
