"""add student parent contact and section

Revision ID: 4d1b0b81d2b9
Revises: c869ac6dbcd3
Create Date: 2025-12-29 16:13:28.171712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1b0b81d2b9'
down_revision: Union[str, None] = 'c869ac6dbcd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add columns as nullable first
    op.add_column(
        "students",
        sa.Column("parent_phone", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "students",
        sa.Column("parent_name", sa.String(length=255), nullable=True),
    )

    # 2. Backfill parent_phone for existing rows (pilot-safe default)
    op.execute(
        "UPDATE students SET parent_phone = '+910000000000' WHERE parent_phone IS NULL"
    )

    # 3. Enforce NOT NULL after data is safe
    op.alter_column(
        "students",
        "parent_phone",
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column(
        'school_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_school_id_fkey', 'students', 'schools', [
                          'school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_students_section_id'), table_name='students')
    op.create_index('ix_students_school_id', 'students',
                    ['school_id'], unique=False)
    op.drop_column('students', 'parent_name')
    op.drop_column('students', 'parent_phone')
    op.drop_column('students', 'section_id')
    # ### end Alembic commands ###
