"""create full schema

Revision ID: 4e8114d023db
Revises: 0adc927708c8
Create Date: 2026-03-04 16:53:04.908434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8114d023db'
down_revision: Union[str, None] = '0adc927708c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_id'), 'otp_requests', ['id'], unique=False)
    op.create_index(op.f('ix_otp_requests_phone'), 'otp_requests', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_create_school', sa.Boolean(), nullable=False),
    sa.Column('max_schools', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', 'key', name='uq_idempotency_user_scope_key')
    )
    op.create_index(op.f('ix_idempotency_keys_id'), 'idempotency_keys', ['id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_scope'), 'idempotency_keys', ['scope'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('school_onboarding_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_onboarding_drafts_id'), 'school_onboarding_drafts', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('board', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('medium', sa.String(length=64), nullable=True),
    sa.Column('school_type', sa.String(length=64), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('affiliation_number', sa.String(length=64), nullable=True),
    sa.Column('udise_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_index(op.f('ix_schools_udise_code'), 'schools', ['udise_code'], unique=True)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('management_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('language_preference', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'user_id', name='uq_management_admin_school_user')
    )
    op.create_index(op.f('ix_management_admins_id'), 'management_admins', ['id'], unique=False)
    op.create_index(op.f('ix_management_admins_school_id'), 'management_admins', ['school_id'], unique=False)
    op.create_index(op.f('ix_management_admins_user_id'), 'management_admins', ['user_id'], unique=False)
    op.create_table('principal_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('replaced_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principal_assignment_history_id'), 'principal_assignment_history', ['id'], unique=False)
    op.create_index(op.f('ix_principal_assignment_history_replaced_by_user_id'), 'principal_assignment_history', ['replaced_by_user_id'], unique=False)
    op.create_index(op.f('ix_principal_assignment_history_school_id'), 'principal_assignment_history', ['school_id'], unique=False)
    op.create_index(op.f('ix_principal_assignment_history_status'), 'principal_assignment_history', ['status'], unique=False)
    op.create_index(op.f('ix_principal_assignment_history_user_id'), 'principal_assignment_history', ['user_id'], unique=False)
    op.create_table('principal_onboarding_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principal_onboarding_sessions_id'), 'principal_onboarding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_principal_onboarding_sessions_phone'), 'principal_onboarding_sessions', ['phone'], unique=False)
    op.create_index(op.f('ix_principal_onboarding_sessions_requested_by_user_id'), 'principal_onboarding_sessions', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_principal_onboarding_sessions_school_id'), 'principal_onboarding_sessions', ['school_id'], unique=False)
    op.create_table('school_academic_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('current_session', sa.String(length=64), nullable=True),
    sa.Column('academic_start_month', sa.Integer(), nullable=True),
    sa.Column('academic_end_month', sa.Integer(), nullable=True),
    sa.Column('working_days_per_week', sa.Integer(), nullable=True),
    sa.Column('class_levels', sa.JSON(), nullable=True),
    sa.Column('lkg_available', sa.Boolean(), nullable=False),
    sa.Column('ukg_available', sa.Boolean(), nullable=False),
    sa.Column('pre_nursery_available', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', name='uq_school_academic_details_school_id')
    )
    op.create_index(op.f('ix_school_academic_details_id'), 'school_academic_details', ['id'], unique=False)
    op.create_index(op.f('ix_school_academic_details_school_id'), 'school_academic_details', ['school_id'], unique=False)
    op.create_table('school_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('pin_code', sa.String(length=12), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('school_phone', sa.String(length=20), nullable=True),
    sa.Column('school_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_email', name='uq_school_contacts_school_email'),
    sa.UniqueConstraint('school_id', name='uq_school_contacts_school_id')
    )
    op.create_index(op.f('ix_school_contacts_id'), 'school_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_school_contacts_school_id'), 'school_contacts', ['school_id'], unique=False)
    op.create_table('school_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('modules_enabled', sa.JSON(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('max_teachers', sa.Integer(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=True),
    sa.Column('api_access', sa.Boolean(), nullable=False),
    sa.Column('bulk_operations', sa.Boolean(), nullable=False),
    sa.Column('custom_reports', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', name='uq_school_features_school_id')
    )
    op.create_index(op.f('ix_school_features_id'), 'school_features', ['id'], unique=False)
    op.create_index(op.f('ix_school_features_school_id'), 'school_features', ['school_id'], unique=False)
    op.create_table('student_import_batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_committed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_import_batches_id'), 'student_import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_student_import_batches_school_id'), 'student_import_batches', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_import_batches_user_id'), 'student_import_batches', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_table('user_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_schools_id'), 'user_schools', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_class_id'), 'sections', ['class_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_school_id'), 'sections', ['school_id'], unique=False)
    op.create_table('attendance_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'section_id', 'date', name='uq_att_sub_school_section_date')
    )
    op.create_index(op.f('ix_attendance_submissions_date'), 'attendance_submissions', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_id'), 'attendance_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_school_id'), 'attendance_submissions', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_section_id'), 'attendance_submissions', ['section_id'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_submitted_by_user_id'), 'attendance_submissions', ['submitted_by_user_id'], unique=False)
    op.create_table('homework_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_broadcasts_created_by_user_id'), 'homework_broadcasts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_id'), 'homework_broadcasts', ['id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_school_id'), 'homework_broadcasts', ['school_id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_section_id'), 'homework_broadcasts', ['section_id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_subject_id'), 'homework_broadcasts', ['subject_id'], unique=False)
    op.create_table('marks_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=32), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'section_id', 'subject_id', 'exam_type', name='uq_marks_sub_school_section_subject_exam')
    )
    op.create_index(op.f('ix_marks_submissions_exam_type'), 'marks_submissions', ['exam_type'], unique=False)
    op.create_index(op.f('ix_marks_submissions_id'), 'marks_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_school_id'), 'marks_submissions', ['school_id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_section_id'), 'marks_submissions', ['section_id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_subject_id'), 'marks_submissions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_submitted_by_user_id'), 'marks_submissions', ['submitted_by_user_id'], unique=False)
    op.create_table('parent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_messages_created_by_user_id'), 'parent_messages', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_parent_messages_id'), 'parent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_parent_messages_school_id'), 'parent_messages', ['school_id'], unique=False)
    op.create_index(op.f('ix_parent_messages_section_id'), 'parent_messages', ['section_id'], unique=False)
    op.create_table('section_subject_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'section_id', 'subject_id', name='uq_sst_school_section_subject')
    )
    op.create_index(op.f('ix_section_subject_teachers_id'), 'section_subject_teachers', ['id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_school_id'), 'section_subject_teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_section_id'), 'section_subject_teachers', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_subject_id'), 'section_subject_teachers', ['subject_id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_teacher_id'), 'section_subject_teachers', ['teacher_id'], unique=False)
    op.create_index('ix_sst_school_section', 'section_subject_teachers', ['school_id', 'section_id'], unique=False)
    op.create_index('ix_sst_school_teacher', 'section_subject_teachers', ['school_id', 'teacher_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('roll_number', sa.String(length=32), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('parent_phone', sa.String(length=32), nullable=False),
    sa.Column('parent_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_index(op.f('ix_students_section_id'), 'students', ['section_id'], unique=False)
    op.create_table('teacher_primary_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'teacher_id', name='uq_tps_school_teacher')
    )
    op.create_index(op.f('ix_teacher_primary_sections_school_id'), 'teacher_primary_sections', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_primary_sections_section_id'), 'teacher_primary_sections', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_primary_sections_teacher_id'), 'teacher_primary_sections', ['teacher_id'], unique=False)
    op.create_index('ix_tps_school_teacher', 'teacher_primary_sections', ['school_id', 'teacher_id'], unique=False)
    op.create_table('teacher_section_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('is_primary_teacher', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_user_id', 'section_id', 'subject_name', name='uq_teacher_section_subject')
    )
    op.create_index(op.f('ix_teacher_section_assignments_id'), 'teacher_section_assignments', ['id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('marked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'date', name='uq_attendance_school_student_date')
    )
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_marked_by_user_id'), 'attendance_records', ['marked_by_user_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_school_id'), 'attendance_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_index('ix_attendance_school_date', 'attendance_records', ['school_id', 'date'], unique=False)
    op.create_index('ix_attendance_school_student', 'attendance_records', ['school_id', 'student_id'], unique=False)
    op.create_table('marks_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=32), nullable=False),
    sa.Column('marks_obtained', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'subject_id', 'exam_type', name='uq_marks_school_student_subject_exam')
    )
    op.create_index(op.f('ix_marks_records_exam_type'), 'marks_records', ['exam_type'], unique=False)
    op.create_index(op.f('ix_marks_records_id'), 'marks_records', ['id'], unique=False)
    op.create_index(op.f('ix_marks_records_recorded_by_user_id'), 'marks_records', ['recorded_by_user_id'], unique=False)
    op.create_index(op.f('ix_marks_records_school_id'), 'marks_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_marks_records_student_id'), 'marks_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_marks_records_subject_id'), 'marks_records', ['subject_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('attendance_submission_id', sa.Integer(), nullable=True),
    sa.Column('marks_submission_id', sa.Integer(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(attendance_submission_id IS NOT NULL AND marks_submission_id IS NULL) OR (attendance_submission_id IS NULL AND marks_submission_id IS NOT NULL)', name='ck_outbox_exactly_one_submission_fk'),
    sa.ForeignKeyConstraint(['attendance_submission_id'], ['attendance_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marks_submission_id'], ['marks_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_attendance_submission_id'), 'notification_outbox', ['attendance_submission_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_event_type'), 'notification_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_outbox_id'), 'notification_outbox', ['id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_marks_submission_id'), 'notification_outbox', ['marks_submission_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_next_attempt_at'), 'notification_outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_recipient_phone'), 'notification_outbox', ['recipient_phone'], unique=False)
    op.create_index(op.f('ix_notification_outbox_school_id'), 'notification_outbox', ['school_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_index('uq_outbox_attendance_dedupe', 'notification_outbox', ['event_type', 'attendance_submission_id', 'recipient_phone'], unique=True, postgresql_where='attendance_submission_id IS NOT NULL')
    op.create_index('uq_outbox_marks_dedupe', 'notification_outbox', ['event_type', 'marks_submission_id', 'recipient_phone'], unique=True, postgresql_where='marks_submission_id IS NOT NULL')
    op.create_table('parent_message_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['parent_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_message_recipients_id'), 'parent_message_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_parent_message_recipients_message_id'), 'parent_message_recipients', ['message_id'], unique=False)
    op.create_index(op.f('ix_parent_message_recipients_student_id'), 'parent_message_recipients', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_message_recipients_student_id'), table_name='parent_message_recipients')
    op.drop_index(op.f('ix_parent_message_recipients_message_id'), table_name='parent_message_recipients')
    op.drop_index(op.f('ix_parent_message_recipients_id'), table_name='parent_message_recipients')
    op.drop_table('parent_message_recipients')
    op.drop_index('uq_outbox_marks_dedupe', table_name='notification_outbox', postgresql_where='marks_submission_id IS NOT NULL')
    op.drop_index('uq_outbox_attendance_dedupe', table_name='notification_outbox', postgresql_where='attendance_submission_id IS NOT NULL')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_school_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_recipient_phone'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_next_attempt_at'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_marks_submission_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_event_type'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_attendance_submission_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_marks_records_subject_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_student_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_school_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_recorded_by_user_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_exam_type'), table_name='marks_records')
    op.drop_table('marks_records')
    op.drop_index('ix_attendance_school_student', table_name='attendance_records')
    op.drop_index('ix_attendance_school_date', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_school_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_marked_by_user_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_teacher_section_assignments_id'), table_name='teacher_section_assignments')
    op.drop_table('teacher_section_assignments')
    op.drop_index('ix_tps_school_teacher', table_name='teacher_primary_sections')
    op.drop_index(op.f('ix_teacher_primary_sections_teacher_id'), table_name='teacher_primary_sections')
    op.drop_index(op.f('ix_teacher_primary_sections_section_id'), table_name='teacher_primary_sections')
    op.drop_index(op.f('ix_teacher_primary_sections_school_id'), table_name='teacher_primary_sections')
    op.drop_table('teacher_primary_sections')
    op.drop_index(op.f('ix_students_section_id'), table_name='students')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index('ix_sst_school_teacher', table_name='section_subject_teachers')
    op.drop_index('ix_sst_school_section', table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_teacher_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_subject_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_section_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_school_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_id'), table_name='section_subject_teachers')
    op.drop_table('section_subject_teachers')
    op.drop_index(op.f('ix_parent_messages_section_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_school_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_created_by_user_id'), table_name='parent_messages')
    op.drop_table('parent_messages')
    op.drop_index(op.f('ix_marks_submissions_submitted_by_user_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_subject_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_section_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_school_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_exam_type'), table_name='marks_submissions')
    op.drop_table('marks_submissions')
    op.drop_index(op.f('ix_homework_broadcasts_subject_id'), table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_section_id'), table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_school_id'), table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_id'), table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_created_by_user_id'), table_name='homework_broadcasts')
    op.drop_table('homework_broadcasts')
    op.drop_index(op.f('ix_attendance_submissions_submitted_by_user_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_section_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_school_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_date'), table_name='attendance_submissions')
    op.drop_table('attendance_submissions')
    op.drop_index(op.f('ix_sections_school_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_class_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_user_schools_id'), table_name='user_schools')
    op.drop_table('user_schools')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_student_import_batches_user_id'), table_name='student_import_batches')
    op.drop_index(op.f('ix_student_import_batches_school_id'), table_name='student_import_batches')
    op.drop_index(op.f('ix_student_import_batches_id'), table_name='student_import_batches')
    op.drop_table('student_import_batches')
    op.drop_index(op.f('ix_school_features_school_id'), table_name='school_features')
    op.drop_index(op.f('ix_school_features_id'), table_name='school_features')
    op.drop_table('school_features')
    op.drop_index(op.f('ix_school_contacts_school_id'), table_name='school_contacts')
    op.drop_index(op.f('ix_school_contacts_id'), table_name='school_contacts')
    op.drop_table('school_contacts')
    op.drop_index(op.f('ix_school_academic_details_school_id'), table_name='school_academic_details')
    op.drop_index(op.f('ix_school_academic_details_id'), table_name='school_academic_details')
    op.drop_table('school_academic_details')
    op.drop_index(op.f('ix_principal_onboarding_sessions_school_id'), table_name='principal_onboarding_sessions')
    op.drop_index(op.f('ix_principal_onboarding_sessions_requested_by_user_id'), table_name='principal_onboarding_sessions')
    op.drop_index(op.f('ix_principal_onboarding_sessions_phone'), table_name='principal_onboarding_sessions')
    op.drop_index(op.f('ix_principal_onboarding_sessions_id'), table_name='principal_onboarding_sessions')
    op.drop_table('principal_onboarding_sessions')
    op.drop_index(op.f('ix_principal_assignment_history_user_id'), table_name='principal_assignment_history')
    op.drop_index(op.f('ix_principal_assignment_history_status'), table_name='principal_assignment_history')
    op.drop_index(op.f('ix_principal_assignment_history_school_id'), table_name='principal_assignment_history')
    op.drop_index(op.f('ix_principal_assignment_history_replaced_by_user_id'), table_name='principal_assignment_history')
    op.drop_index(op.f('ix_principal_assignment_history_id'), table_name='principal_assignment_history')
    op.drop_table('principal_assignment_history')
    op.drop_index(op.f('ix_management_admins_user_id'), table_name='management_admins')
    op.drop_index(op.f('ix_management_admins_school_id'), table_name='management_admins')
    op.drop_index(op.f('ix_management_admins_id'), table_name='management_admins')
    op.drop_table('management_admins')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_schools_udise_code'), table_name='schools')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_school_onboarding_drafts_id'), table_name='school_onboarding_drafts')
    op.drop_table('school_onboarding_drafts')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_scope'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_requests_phone'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_id'), table_name='otp_requests')
    op.drop_table('otp_requests')
    # ### end Alembic commands ###
