"""fix_user_nullable_constraint

Revision ID: 57bccf7e6e42
Revises: f68d2ccd85ae
Create Date: 2026-01-27 23:26:15.871877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bccf7e6e42'
down_revision: Union[str, None] = 'f68d2ccd85ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column as nullable first
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))

    # 2. Set the default value for all existing rows
    op.execute("UPDATE users SET is_active = True")

    # 3. Now make it NOT NULL
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
