"""create marks records and submissions tables

Revision ID: 72c57d77456d
Revises: 79132501e241
Create Date: 2025-12-29 15:12:15.730587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c57d77456d'
down_revision: Union[str, None] = '79132501e241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=32), nullable=False),
    sa.Column('marks_obtained', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'subject_id', 'exam_type', name='uq_marks_school_student_subject_exam')
    )
    op.create_index(op.f('ix_marks_records_exam_type'), 'marks_records', ['exam_type'], unique=False)
    op.create_index(op.f('ix_marks_records_id'), 'marks_records', ['id'], unique=False)
    op.create_index(op.f('ix_marks_records_recorded_by_user_id'), 'marks_records', ['recorded_by_user_id'], unique=False)
    op.create_index(op.f('ix_marks_records_school_id'), 'marks_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_marks_records_student_id'), 'marks_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_marks_records_subject_id'), 'marks_records', ['subject_id'], unique=False)
    op.create_table('marks_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=32), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'section_id', 'subject_id', 'exam_type', name='uq_marks_sub_school_section_subject_exam')
    )
    op.create_index(op.f('ix_marks_submissions_exam_type'), 'marks_submissions', ['exam_type'], unique=False)
    op.create_index(op.f('ix_marks_submissions_id'), 'marks_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_school_id'), 'marks_submissions', ['school_id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_section_id'), 'marks_submissions', ['section_id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_subject_id'), 'marks_submissions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_marks_submissions_submitted_by_user_id'), 'marks_submissions', ['submitted_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marks_submissions_submitted_by_user_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_subject_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_section_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_school_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_id'), table_name='marks_submissions')
    op.drop_index(op.f('ix_marks_submissions_exam_type'), table_name='marks_submissions')
    op.drop_table('marks_submissions')
    op.drop_index(op.f('ix_marks_records_subject_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_student_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_school_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_recorded_by_user_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_id'), table_name='marks_records')
    op.drop_index(op.f('ix_marks_records_exam_type'), table_name='marks_records')
    op.drop_table('marks_records')
    # ### end Alembic commands ###
