"""add attendance submissions and notification outbox

Revision ID: 75b912a27845
Revises: a7fd0e240560
Create Date: 2025-12-29 13:46:20.960131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b912a27845'
down_revision: Union[str, None] = 'a7fd0e240560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'section_id', 'date', name='uq_att_sub_school_section_date')
    )
    op.create_index(op.f('ix_attendance_submissions_date'), 'attendance_submissions', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_id'), 'attendance_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_school_id'), 'attendance_submissions', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_section_id'), 'attendance_submissions', ['section_id'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_submitted_by_user_id'), 'attendance_submissions', ['submitted_by_user_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['attendance_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'student_id', 'channel', name='uq_outbox_submission_student_channel')
    )
    op.create_index(op.f('ix_notification_outbox_id'), 'notification_outbox', ['id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_student_id'), 'notification_outbox', ['student_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_submission_id'), 'notification_outbox', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_outbox_submission_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_student_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_attendance_submissions_submitted_by_user_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_section_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_school_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_id'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_date'), table_name='attendance_submissions')
    op.drop_table('attendance_submissions')
    # ### end Alembic commands ###
