"""create section_subject_teachers table

Revision ID: b81809ab7aaf
Revises: f7a2fa09402b
Create Date: 2026-01-13 02:22:33.315385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b81809ab7aaf'
down_revision: Union[str, None] = 'f7a2fa09402b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_subject_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'section_id', 'subject_id', name='uq_sst_school_section_subject')
    )
    op.create_index(op.f('ix_section_subject_teachers_id'), 'section_subject_teachers', ['id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_school_id'), 'section_subject_teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_section_id'), 'section_subject_teachers', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_subject_id'), 'section_subject_teachers', ['subject_id'], unique=False)
    op.create_index(op.f('ix_section_subject_teachers_teacher_id'), 'section_subject_teachers', ['teacher_id'], unique=False)
    op.create_index('ix_sst_school_section', 'section_subject_teachers', ['school_id', 'section_id'], unique=False)
    op.create_index('ix_sst_school_teacher', 'section_subject_teachers', ['school_id', 'teacher_id'], unique=False)
    op.drop_index('ix_student_notes_school_student', table_name='student_notes')
    op.drop_table('student_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name='student_notes_author_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='student_notes_school_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_notes_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student_notes_pkey')
    )
    op.create_index('ix_student_notes_school_student', 'student_notes', ['school_id', 'student_id'], unique=False)
    op.drop_index('ix_sst_school_teacher', table_name='section_subject_teachers')
    op.drop_index('ix_sst_school_section', table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_teacher_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_subject_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_section_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_school_id'), table_name='section_subject_teachers')
    op.drop_index(op.f('ix_section_subject_teachers_id'), table_name='section_subject_teachers')
    op.drop_table('section_subject_teachers')
    # ### end Alembic commands ###
