"""create student notes table

Revision ID: bda3316a578e
Revises: 57bccf7e6e42
Create Date: 2026-01-30 01:17:36.347252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bda3316a578e'
down_revision: Union[str, None] = '57bccf7e6e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_schools', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_index('idx_user_schools_user_id', table_name='user_schools')
    op.drop_constraint('user_schools_user_id_school_id_key', 'user_schools', type_='unique')
    op.create_index(op.f('ix_user_schools_id'), 'user_schools', ['id'], unique=False)
    op.drop_column('user_schools', 'created_at')
    op.drop_index('ix_users_school_id', table_name='users')
    op.drop_constraint('users_school_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_school_id_fkey', 'users', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_users_school_id', 'users', ['school_id'], unique=False)
    op.add_column('user_schools', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_schools_id'), table_name='user_schools')
    op.create_unique_constraint('user_schools_user_id_school_id_key', 'user_schools', ['user_id', 'school_id'])
    op.create_index('idx_user_schools_user_id', 'user_schools', ['user_id'], unique=False)
    op.alter_column('user_schools', 'role',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
