"""create notification outbox table

Revision ID: c869ac6dbcd3
Revises: 72c57d77456d
Create Date: 2025-12-29 15:44:37.270273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c869ac6dbcd3'
down_revision: Union[str, None] = '72c57d77456d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_outbox', sa.Column('school_id', sa.Integer(), nullable=False))
    op.add_column('notification_outbox', sa.Column('event_type', sa.String(length=64), nullable=False))
    op.add_column('notification_outbox', sa.Column('attendance_submission_id', sa.Integer(), nullable=True))
    op.add_column('notification_outbox', sa.Column('marks_submission_id', sa.Integer(), nullable=True))
    op.add_column('notification_outbox', sa.Column('recipient_phone', sa.String(length=32), nullable=False))
    op.add_column('notification_outbox', sa.Column('payload', sa.Text(), nullable=False))
    op.add_column('notification_outbox', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('notification_outbox', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('notification_outbox', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.drop_index('ix_notification_outbox_student_id', table_name='notification_outbox')
    op.drop_index('ix_notification_outbox_submission_id', table_name='notification_outbox')
    op.drop_constraint('uq_outbox_submission_student_channel', 'notification_outbox', type_='unique')
    op.create_index(op.f('ix_notification_outbox_attendance_submission_id'), 'notification_outbox', ['attendance_submission_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_event_type'), 'notification_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_outbox_marks_submission_id'), 'notification_outbox', ['marks_submission_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_recipient_phone'), 'notification_outbox', ['recipient_phone'], unique=False)
    op.create_index(op.f('ix_notification_outbox_school_id'), 'notification_outbox', ['school_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_index('uq_outbox_attendance_dedupe', 'notification_outbox', ['event_type', 'attendance_submission_id', 'recipient_phone'], unique=True, postgresql_where='attendance_submission_id IS NOT NULL')
    op.create_index('uq_outbox_marks_dedupe', 'notification_outbox', ['event_type', 'marks_submission_id', 'recipient_phone'], unique=True, postgresql_where='marks_submission_id IS NOT NULL')
    op.drop_constraint('notification_outbox_submission_id_fkey', 'notification_outbox', type_='foreignkey')
    op.drop_constraint('notification_outbox_student_id_fkey', 'notification_outbox', type_='foreignkey')
    op.create_foreign_key(None, 'notification_outbox', 'marks_submissions', ['marks_submission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification_outbox', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification_outbox', 'attendance_submissions', ['attendance_submission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notification_outbox', 'submission_id')
    op.drop_column('notification_outbox', 'student_id')
    op.drop_column('notification_outbox', 'channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_outbox', sa.Column('channel', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('notification_outbox', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notification_outbox', sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notification_outbox', type_='foreignkey')
    op.drop_constraint(None, 'notification_outbox', type_='foreignkey')
    op.drop_constraint(None, 'notification_outbox', type_='foreignkey')
    op.create_foreign_key('notification_outbox_student_id_fkey', 'notification_outbox', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notification_outbox_submission_id_fkey', 'notification_outbox', 'attendance_submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_outbox_marks_dedupe', table_name='notification_outbox', postgresql_where='marks_submission_id IS NOT NULL')
    op.drop_index('uq_outbox_attendance_dedupe', table_name='notification_outbox', postgresql_where='attendance_submission_id IS NOT NULL')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_school_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_recipient_phone'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_marks_submission_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_event_type'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_attendance_submission_id'), table_name='notification_outbox')
    op.create_unique_constraint('uq_outbox_submission_student_channel', 'notification_outbox', ['submission_id', 'student_id', 'channel'])
    op.create_index('ix_notification_outbox_submission_id', 'notification_outbox', ['submission_id'], unique=False)
    op.create_index('ix_notification_outbox_student_id', 'notification_outbox', ['student_id'], unique=False)
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('notification_outbox', 'sent_at')
    op.drop_column('notification_outbox', 'last_error')
    op.drop_column('notification_outbox', 'attempts')
    op.drop_column('notification_outbox', 'payload')
    op.drop_column('notification_outbox', 'recipient_phone')
    op.drop_column('notification_outbox', 'marks_submission_id')
    op.drop_column('notification_outbox', 'attendance_submission_id')
    op.drop_column('notification_outbox', 'event_type')
    op.drop_column('notification_outbox', 'school_id')
    # ### end Alembic commands ###
