"""baseline_schema

Revision ID: ca93147aa3b6
Revises: 
Create Date: 2026-03-04 14:53:46.382071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca93147aa3b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_student_notes_school_student")
    op.drop_table('student_notes')
    op.drop_index('ix_principals_school_id', table_name='principals')
    op.drop_table('principals')
    op.drop_index('ix_homework_broadcasts_school_section',
                  table_name='homework_broadcasts')
    op.create_index(op.f('ix_homework_broadcasts_created_by_user_id'),
                    'homework_broadcasts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_id'),
                    'homework_broadcasts', ['id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_school_id'),
                    'homework_broadcasts', ['school_id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_section_id'),
                    'homework_broadcasts', ['section_id'], unique=False)
    op.create_index(op.f('ix_homework_broadcasts_subject_id'),
                    'homework_broadcasts', ['subject_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_id'),
                    'idempotency_keys', ['id'], unique=False)
    op.create_index(op.f('ix_management_admins_id'),
                    'management_admins', ['id'], unique=False)
    op.drop_index('ix_otp_requests_phone_created_at_desc',
                  table_name='otp_requests')
    op.drop_index('ix_otp_requests_phone_status', table_name='otp_requests')
    op.drop_index('ix_parent_message_recipients_message_student',
                  table_name='parent_message_recipients')
    op.create_index(op.f('ix_parent_message_recipients_id'),
                    'parent_message_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_parent_message_recipients_message_id'),
                    'parent_message_recipients', ['message_id'], unique=False)
    op.create_index(op.f('ix_parent_message_recipients_student_id'),
                    'parent_message_recipients', ['student_id'], unique=False)
    op.drop_index('ix_parent_messages_school_section',
                  table_name='parent_messages')
    op.create_index(op.f('ix_parent_messages_created_by_user_id'),
                    'parent_messages', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_parent_messages_id'),
                    'parent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_parent_messages_school_id'),
                    'parent_messages', ['school_id'], unique=False)
    op.create_index(op.f('ix_parent_messages_section_id'),
                    'parent_messages', ['section_id'], unique=False)
    op.create_index(op.f('ix_principal_assignment_history_id'),
                    'principal_assignment_history', ['id'], unique=False)
    op.create_index(op.f('ix_principal_onboarding_sessions_id'),
                    'principal_onboarding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_school_academic_details_id'),
                    'school_academic_details', ['id'], unique=False)
    op.create_index(op.f('ix_school_contacts_id'),
                    'school_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_school_features_id'),
                    'school_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_features_id'), table_name='school_features')
    op.drop_index(op.f('ix_school_contacts_id'), table_name='school_contacts')
    op.drop_index(op.f('ix_school_academic_details_id'),
                  table_name='school_academic_details')
    op.drop_index(op.f('ix_principal_onboarding_sessions_id'),
                  table_name='principal_onboarding_sessions')
    op.drop_index(op.f('ix_principal_assignment_history_id'),
                  table_name='principal_assignment_history')
    op.drop_index(op.f('ix_parent_messages_section_id'),
                  table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_school_id'),
                  table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_created_by_user_id'),
                  table_name='parent_messages')
    op.create_index('ix_parent_messages_school_section', 'parent_messages', [
                    'school_id', 'section_id'], unique=False)
    op.drop_index(op.f('ix_parent_message_recipients_student_id'),
                  table_name='parent_message_recipients')
    op.drop_index(op.f('ix_parent_message_recipients_message_id'),
                  table_name='parent_message_recipients')
    op.drop_index(op.f('ix_parent_message_recipients_id'),
                  table_name='parent_message_recipients')
    op.create_index('ix_parent_message_recipients_message_student',
                    'parent_message_recipients', ['message_id', 'student_id'], unique=True)
    op.create_index('ix_otp_requests_phone_status', 'otp_requests', [
                    'phone', 'status'], unique=False)
    op.create_index('ix_otp_requests_phone_created_at_desc', 'otp_requests', [
                    'phone', sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_management_admins_id'),
                  table_name='management_admins')
    op.drop_index(op.f('ix_idempotency_keys_id'),
                  table_name='idempotency_keys')
    op.drop_index(op.f('ix_homework_broadcasts_subject_id'),
                  table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_section_id'),
                  table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_school_id'),
                  table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_id'),
                  table_name='homework_broadcasts')
    op.drop_index(op.f('ix_homework_broadcasts_created_by_user_id'),
                  table_name='homework_broadcasts')
    op.create_index('ix_homework_broadcasts_school_section', 'homework_broadcasts', [
                    'school_id', 'section_id'], unique=False)
    op.create_table('principals',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('school_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=200),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['school_id'], [
                        'schools.id'], name='principals_school_id_fkey', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name='principals_user_id_fkey', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id', name='principals_pkey'),
                    sa.UniqueConstraint(
                        'school_id', name='uq_principals_school_id'),
                    sa.UniqueConstraint(
                        'user_id', name='uq_principals_user_id')
                    )
    op.create_index('ix_principals_school_id', 'principals',
                    ['school_id'], unique=False)
    op.create_table('student_notes',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('school_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('student_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('author_user_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('note_text', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['author_user_id'], [
                        'users.id'], name='student_notes_author_user_id_fkey', ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['school_id'], [
                        'schools.id'], name='student_notes_school_id_fkey', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['student_id'], [
                        'students.id'], name='student_notes_student_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='student_notes_pkey')
                    )
    op.create_index('ix_student_notes_school_student', 'student_notes', [
                    'school_id', 'student_id'], unique=False)
    # ### end Alembic commands ###
