"""create teacher section assignments table

Revision ID: dab635796bdb
Revises: bda3316a578e
Create Date: 2026-01-30 01:43:48.114128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dab635796bdb'
down_revision: Union[str, None] = 'bda3316a578e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_section_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('is_primary_teacher', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_user_id', 'section_id', 'subject_name', name='uq_teacher_section_subject')
    )
    op.create_index(op.f('ix_teacher_section_assignments_id'), 'teacher_section_assignments', ['id'], unique=False)
    op.drop_table('student_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name='fk_author'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='fk_school'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_student'),
    sa.PrimaryKeyConstraint('id', name='student_notes_pkey')
    )
    op.drop_index(op.f('ix_teacher_section_assignments_id'), table_name='teacher_section_assignments')
    op.drop_table('teacher_section_assignments')
    # ### end Alembic commands ###
