"""create teacher_primary_sections

Revision ID: e20cba61afbe
Revises: 884c8272fdc6
Create Date: 2025-12-30 15:28:14.350586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20cba61afbe'
down_revision: Union[str, None] = '884c8272fdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_primary_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'teacher_id', name='uq_tps_school_teacher')
    )
    op.create_index(op.f('ix_teacher_primary_sections_school_id'), 'teacher_primary_sections', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_primary_sections_section_id'), 'teacher_primary_sections', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_primary_sections_teacher_id'), 'teacher_primary_sections', ['teacher_id'], unique=False)
    op.create_index('ix_tps_school_teacher', 'teacher_primary_sections', ['school_id', 'teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tps_school_teacher', table_name='teacher_primary_sections')
    op.drop_index(op.f('ix_teacher_primary_sections_teacher_id'), table_name='teacher_primary_sections')
    op.drop_index(op.f('ix_teacher_primary_sections_section_id'), table_name='teacher_primary_sections')
    op.drop_index(op.f('ix_teacher_primary_sections_school_id'), table_name='teacher_primary_sections')
    op.drop_table('teacher_primary_sections')
    # ### end Alembic commands ###
