"""make_school_id_nullable_for_super_admin

Revision ID: f68d2ccd85ae
Revises: 026034bac710
Create Date: 2026-01-27 22:52:59.431889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f68d2ccd85ae'
down_revision: Union[str, None] = '026034bac710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    table_names = set(inspector.get_table_names())

    if 'principals' in table_names:
        principal_indexes = {i["name"] for i in inspector.get_indexes('principals')}
        if 'ix_principals_school_id' in principal_indexes:
            op.drop_index('ix_principals_school_id', table_name='principals')
        op.drop_table('principals')

    if 'student_notes' in table_names:
        note_indexes = {i["name"] for i in inspector.get_indexes('student_notes')}
        if 'ix_student_notes_school_student' in note_indexes:
            op.drop_index('ix_student_notes_school_student', table_name='student_notes')
        op.drop_table('student_notes')

    if 'notification_outbox' in table_names:
        no_cols = {c["name"] for c in inspector.get_columns('notification_outbox')}
        if 'last_error_code' in no_cols:
            op.drop_column('notification_outbox', 'last_error_code')
        if 'last_error_message' in no_cols:
            op.drop_column('notification_outbox', 'last_error_message')
        if 'provider' in no_cols:
            op.drop_column('notification_outbox', 'provider')
        if 'provider_message_id' in no_cols:
            op.drop_column('notification_outbox', 'provider_message_id')

    if 'teachers' in table_names:
        teacher_cols = {c["name"] for c in inspector.get_columns('teachers')}
        if 'user_id' in teacher_cols:
            op.alter_column('teachers', 'user_id', existing_type=sa.INTEGER(), nullable=False)
        teacher_uniques = {u["name"] for u in inspector.get_unique_constraints('teachers')}
        if 'uq_teachers_user_id' in teacher_uniques:
            op.drop_constraint('uq_teachers_user_id', 'teachers', type_='unique')
        teacher_indexes = {i["name"] for i in inspector.get_indexes('teachers')}
        ix_name = op.f('ix_teachers_user_id')
        if 'user_id' in teacher_cols and ix_name not in teacher_indexes:
            op.create_index(ix_name, 'teachers', ['user_id'], unique=True)

    if 'users' in table_names:
        user_cols = {c["name"] for c in inspector.get_columns('users')}
        if 'school_id' in user_cols:
            op.alter_column('users', 'school_id', existing_type=sa.INTEGER(), nullable=True)
        user_indexes = {i["name"] for i in inspector.get_indexes('users')}
        if 'uq_users_school_email' in user_indexes:
            op.drop_index('uq_users_school_email', table_name='users', postgresql_where='(email IS NOT NULL)')
        if 'is_active' in user_cols:
            op.drop_column('users', 'is_active')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('uq_users_school_email', 'users', ['school_id', 'email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_unique_constraint('uq_teachers_user_id', 'teachers', ['user_id'])
    op.alter_column('teachers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('notification_outbox', sa.Column('provider_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('notification_outbox', sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('notification_outbox', sa.Column('last_error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notification_outbox', sa.Column('last_error_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_table('student_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name='student_notes_author_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='student_notes_school_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_notes_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student_notes_pkey')
    )
    op.create_index('ix_student_notes_school_student', 'student_notes', ['school_id', 'student_id'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='principals_school_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='principals_user_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='principals_pkey'),
    sa.UniqueConstraint('school_id', name='uq_principals_school_id'),
    sa.UniqueConstraint('user_id', name='uq_principals_user_id')
    )
    op.create_index('ix_principals_school_id', 'principals', ['school_id'], unique=False)
    # ### end Alembic commands ###
