"""make_school_id_nullable_for_super_admin

Revision ID: f68d2ccd85ae
Revises: 026034bac710
Create Date: 2026-01-27 22:52:59.431889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f68d2ccd85ae'
down_revision: Union[str, None] = '026034bac710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_principals_school_id', table_name='principals')
    op.drop_table('principals')
    op.drop_index('ix_student_notes_school_student', table_name='student_notes')
    op.drop_table('student_notes')
    op.drop_column('notification_outbox', 'last_error_code')
    op.drop_column('notification_outbox', 'last_error_message')
    op.drop_column('notification_outbox', 'provider')
    op.drop_column('notification_outbox', 'provider_message_id')
    op.alter_column('teachers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_teachers_user_id', 'teachers', type_='unique')
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('uq_users_school_email', table_name='users', postgresql_where='(email IS NOT NULL)')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('uq_users_school_email', 'users', ['school_id', 'email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_unique_constraint('uq_teachers_user_id', 'teachers', ['user_id'])
    op.alter_column('teachers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('notification_outbox', sa.Column('provider_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('notification_outbox', sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('notification_outbox', sa.Column('last_error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notification_outbox', sa.Column('last_error_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_table('student_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name='student_notes_author_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='student_notes_school_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_notes_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student_notes_pkey')
    )
    op.create_index('ix_student_notes_school_student', 'student_notes', ['school_id', 'student_id'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='principals_school_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='principals_user_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='principals_pkey'),
    sa.UniqueConstraint('school_id', name='uq_principals_school_id'),
    sa.UniqueConstraint('user_id', name='uq_principals_user_id')
    )
    op.create_index('ix_principals_school_id', 'principals', ['school_id'], unique=False)
    # ### end Alembic commands ###
